### ISSUE TITLE
OR/AND filter args not working with some other filter args

### ISSUE THREAD

**Issue by fklingler** [graphql-compose/graphql-compose-mongoose#128]
Hi!

I've been working with the filter args, but it seems that you cannot use `_ids` or `_operators` inside an `OR` or `AND` filter, it just doesn't return any result. I don't think this is the expected result, but I may be wrong.

**Comment by nodkz** [comment]
Sorry for missing this issue

Can you create a test case as it did for other issues
https://github.com/graphql-compose/graphql-compose-mongoose/tree/master/src/__tests__/guthub_issues

This is a good CTRL+C CTRL+V candidate for your case: https://github.com/graphql-compose/graphql-compose-mongoose/blob/master/src/__tests__/guthub_issues/120-test.js

**Comment by fklingler** [comment]
I'm not sure I understand what you want me to do with this.
Do you want me to create a PR adding a file testing this case?

**Comment by nodkz** [comment]
Yep, please open PR with broken test 😉

Try to review and fix it tomorrow. Thanks.

**Comment by fklingler** [comment]
I'm sorry but I don't know/understand how to write a test corresponding to my problem.

I'm willing to help and do it, but maybe you could write documentation for this in a CONTRIBUTING file?

**Comment by ham3dz** [comment]
I have the same issue and found the problem.

Suppose we have this mongoose schema:
`let userSchema = new mongoose.Schema({
    name: String,

    pets: [String],

    friends: [String]
});`

We want query over `pets` and `friends` to find users with specific pets **or** friends.
The mongodb query should be this:
`{
    $or: [
        {
            pets: { $in: pets }
        },
        {
            friends: { $in: friends }
        }
    ]
}`

and graphql query should be this:
`query ($pets: [String], $friends: [String]) {
    userMany(filter:{ OR: [{ _operators: { pets: { in: $pets }}}, { _operators: { friends: { in: $friends }}}]}) {
        _id
    }
}`

After enabling mongoose debug found out `graphql-compose-mongoose` translating above query to something like this:
`{
    $or: [
        { "_operators.pets.in": pets},
        { "_operators.friends.in": friends }
    ]
}`

As it's obvious `_operators.pets.in" is meaningless and this happens when `_operators` used with `AND` or `OR`.

**Comment by corydeppen** [comment]
I'm running into the same issue. Using the `_operators` filter outside an `OR` works fine, it just doesn't work inside.

**Comment by corydeppen** [comment]
@nodkz I hope the failing tests in #179 are sufficient to help identify the issue. This is currently a sticking point for my project and I'm unsure if there is a quick fix or workaround to enable filtering using `_operators` inside `AND` and `OR` arrays.
