### ISSUE TITLE
Required properties in Create Resolvers

### ISSUE THREAD

**Issue by israelglar** [graphql-compose/graphql-compose-mongoose#144]
Reposting in right repo from https://github.com/graphql-compose/graphql-compose/issues/151

I have a User schema
```ts
const UserSchema = new Mongoose.Schema(
  {
    email: {type: String, unique: true, required: true},
    name: {type: String, required: true},
  },
  {
    timestamps: true,
  },
);
```
After using `composeWithMongoose` and exposing all CRUD resolvers the result for the Create methods are:
```graphql
type CreateOneUserInput {
  email: String
  name: String
  updatedAt: Date
  createdAt: Date
}
type CreateManyUserInput {
  email: String
  name: String
  updatedAt: Date
  createdAt: Date
}
```
The properties `email` and `name` should be required.

I just recently started using the library, so maybe there is something in docs that I didn't see.
If it's a bug, I can contribute with a fix with some guidance.
Thanks

**Comment by israelglar** [comment]
As I see it, the issue comes from this function and the function is calls:

https://github.com/graphql-compose/graphql-compose-mongoose/blob/04e82c3e326d6ab231b9fc89b166aa199b598c1f/src/fieldsConverter.js#L190-L218

It doesn't check if the field is required and handled

**Comment by nodkz** [comment]
I suggest to you use programmatic way. When types were generated then you may modify them as you wish. In your case you need to run the following code:
```js
UserTC.getResolver('createMany').getArgTC('record'). makeRequired(['email', 'name']);
```

**Comment by israelglar** [comment]
I understand that this is possible, my question is more about why isn't it supported by default with the `composeWithMongoose` function, since that information is already present in the mongoose Schema.

I'm doing some tests with the source code and something like this can be done:

**graphql-compose-mongoose/src/fieldsConverter.js LN138**
```js
Object.keys(mongooseFields).forEach(fieldName => {
    const mongooseField = mongooseFields[fieldName];

    let fieldType = convertFieldToGraphQL(mongooseField, typeName, schemaComposer)

    if (mongooseField.isRequired) {
      if (typeof fieldType === "string") {
        fieldType = fieldType + '!'
      }
    }

    graphqlFields[fieldName] = {
      type: fieldType,
      description: _getFieldDescription(mongooseField),
    };
```

That is something I'm doing right now and it works for some types that are `typeof string`.
I understand that not all results from `convertFieldToGraphQL` are `typeof string`, but I hope you can see the idea.

What do you think about that?

**Comment by nodkz** [comment]
Brilliant! Can your create Pull Request with tests?

**Comment by nodkz** [comment]
Wow good catch. Urgently need to fix this.

**Comment by israelglar** [comment]
What do you think it's a good solution to that? 

We can always go back to what was before, but I still think that making the fields required when the schema changes is nice thing to have.

Maybe alter the resolver so that only the "Create" ones have that check of required fields?

**Comment by nodkz** [comment]
For now only Create resolvers should have required fields. All other args should be as they were for backward compatibility for current users.

It's very bad to update a package and got a broken queries at runtime.

**Comment by israelglar** [comment]
Agree with you. I will fix that tomorrow so that only Create Resolvers have required fields

**Comment by israelglar** [comment]
Created a new PR: https://github.com/graphql-compose/graphql-compose-mongoose/pull/146

**Comment by toverux** [comment]
Just came across this issue since I need that too!
Thanks @israelglar for the PR, I've just upgraded.

I need required fields on the "output" types as well (used as the return types of find queries, in `record` fields, etc) though.
I'll set them by hand for now.

An idea to preserve backward-compatibility would be to add an option to `composeWithMongoose`, like `preserveRequiredFields` that, when set to true, always sets the types as required (except on filter args, etc).
But we can also wait for a breaking change about that in a future major version.

**Comment by nodkz** [comment]
I think that for Output type we can make `required` fields.
They also will be translated to Input type.
BUT we should remove any required fields from filters.

@toverux if you made such changes we can publish a major version. No problem ;)

Also will be amazing if somebody takes care of https://github.com/graphql-compose/graphql-compose-mongoose/issues/121

From my side, I can create new resolver `findByIdDL` and `findByIdsDL` (resolvers with included data-loaders). More info about proper using of dataloaders [here (translated by google from RU)](https://translate.google.com/translate?hl=&sl=ru&tl=en&u=https%3A%2F%2Fgithub.com%2Fnodkz%2Fconf-talks%2Ftree%2Fmaster%2Farticles%2Fgraphql%2Fdataloader)

**Comment by Thammada** [comment]
In my case, I have a required field, but with a default value. Something like this
```js
const UserSchema = new Mongoose.Schema(
  {
    email: {type: String, unique: true, required: true},
    name: {type: String, required: true},
    role: { type: String, enum: ['admin', 'customer'], default: 'customer', required: true }
  },
  {
    timestamps: true,
  },
);
```
Currently, this breaks my mutation with something like "value of required type was not provided"
Should the default value also be set automatically in the input type too?

**Comment by nodkz** [comment]
@toverux I take a look at this ;)

BUT disagree with you. MAYBE-types are safer in runtime rather than we provide NonNull types for now. I don't want to crash somebody apps in runtime. And forcing to do null checks make the client app safer.

The current graphql-compose implementation allows to you modify generated graphql fields/types if you SURE that with your backend data ;) via `makeFieldNonNull(fieldNameOrArray: string | Array<string>)` methods.

Maybe-types are used for now cause `wrapResolve` methods may return `null` value for some checks and it may breaks server schemas. 

So I recommend to you explicitly make fields non-null. And we definitely should consider some new helpers which can make fields with required types.

@toverux can you try `makeFieldNonNull` for your schemas and provide your code here. So we can think, how it can be improved.

Thanks.
