### ISSUE TITLE
Adding Directive to Type

### ISSUE THREAD

**Issue by MDrooker** [graphql-compose/graphql-compose-mongoose#190]
In going over the issue-
<https://github.com/graphql/graphql-js/issues/1343>

I see the discussion around directives and graphql/graphql-compose.

And .getDirectives() was added to graphql-compose TypeComposer.  And can be created via SDL

Im not seeing where we can add Directives to graphql-compose-mongoose created types.  Is that possible?

**Comment by nodkz** [comment]
Nope, it's not possible to add directives to generated types out of the box.
But schema federation is a very interesting theme which should be covered by graphql-compose.

Let close this issue because here nothing to do. When graphql-compose-mongoose generates the type you able to modify it via standard graphql-compose methods.

Continue the discussion about Federation in core package https://github.com/graphql-compose/graphql-compose/issues/214
