### ISSUE TITLE
How to use the in[] operator in query?

### ISSUE THREAD

**Issue by danielmahon** [graphql-compose/graphql-compose-mongoose#8]
How do you use the `in[]` operator in a query? I can't figure out how to filter a `findMany` resolver to   search by multiple values for a single field. Thanks!

**Comment by nodkz** [comment]
First of all I do not recommend to use `args.filter._operators`. It too tricky for query construction and serving this logic on the client side. So I want to remove them in future.

Instead of I suggest to you another flexible and more controllable solution `Resolver. addFilterArg`:
https://github.com/nodkz/graphql-compose/issues/22 (the first my comment contains a bunch of working examples, this proposal realized already and works perfectly for my use cases).

Also after extending filtering, you may need to extend sorting via `Resolver.addSortArg`:
https://github.com/nodkz/graphql-compose/issues/26

**Comment by yoadsn** [comment]
So we can close this - a concrete simplified example:

```
TC.setResolver('findMany', TC.get('$findMany')
.addFilterArg({
  name: 'tagsIn',
  type: '[String]',
  query: (query, value) => {
    query.tags = { $in: value }
  }
})
```

Assuming the queried document contains a `tags` field and you are OK with overwriting the original generated `findMany` resolver.
